seed_everything: 42

data:
  path: env/ml-100k
  train_partition: u1.base
  val_partition: u1.test
  batch_size: 32
  shuffle: true
  num_workers: 3

model:
  keys: ["user_id", "item_id", "gender", "occupation", "genres"]
  embedding_bag_collection:
    init_args:
      tables:
        - num_embeddings: 944
          embedding_dim: 64
          name: "t_user_id"
          feature_names: ["user_id"]
        - num_embeddings: 1683
          embedding_dim: 64
          name: "t_item_id"
          feature_names: ["item_id"]
        - num_embeddings: 3
          embedding_dim: 64
          name: "t_gender"
          feature_names: ["gender"]
        - num_embeddings: 22
          embedding_dim: 64
          name: "t_occupation"
          feature_names: ["occupation"]
        - num_embeddings: 19
          embedding_dim: 64
          name: "t_genres"
          feature_names: ["genres"]
  dense_in_features: 2
  dense_arch_layer_sizes: [512, 256, 64]
  over_arch_layer_sizes: [512, 512, 256, 1]

trainer:
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: "val_loss"
        patience: 5
        mode: "min"
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: "val_loss"
        mode: "min"
        dirpath: "env/"
        filename: "dlrm-ml_100k-{epoch:02d}-{global_step}-{val_loss:.2f}"
  max_epochs: 30
  deterministic: true

